[tool.ruff]

# Enable all rules from the "pylint" plugin
plugins = ["pylint"]

# Use the default "strict" severity level for pylint rules
pylint = { severity = "strict" }

# Exclude any third-party libraries from linting
exclude = [
    "**/venv/**",
    "**/.virtualenv/**",
    "**/node_modules/**",
    "build/",
    "dist/",
]